
--------------------------------------------------------------
-- Database table removal script

-- Auto-Generated by QSEE-SuperLite (c) 2001-2004 QSEE-Technologies Ltd.

-- note: spaces within table names have been replaced by underscores (_)

-- Target DB: SQL2

-- Entity Model :Entity Relationship Diagram

-- Use this script to drop the tables created by -
--   'C:\Users\LENOVO\Desktop\ddl part 2\dimension_ddl.sql'

-- Dropping a table has the effect of removing it from the Database.  All existing data is lost
-- as well as the definition of the table itself (stored as meta-data).  Dropping the tables allows
-- them to be re-created within the Database, even if they already exist.


--------------------------------------------------------------

-- Drop tables --

DROP TABLE DIM_TIME;

DROP TABLE DIM_CASE;

DROP TABLE DIM_REGION;

DROP TABLE DIM_OFFICER;

DROP TABLE DIM_STATION;

DROP TABLE FACT_CRIME;

DROP TABLE DIM_WITNESS;


--------------------------------------------------------------
-- End of DDL DROP file auto-generation
--------------------------------------------------------------
